apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf2
  labels:
    app: pf2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pf2
  template:
    metadata:
      labels:
        app: pf2
    spec:
      containers:
      - name: pf2
        image: pf2:021c651
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 64Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
