# init container 실습 — init이 끝나야(exit 0) main(nginx)이 시작된다
apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
  - name: wait-something
    image: busybox
    command: ["sh", "-c", "echo init 작업 시작; sleep 10; echo init 완료"]
  containers:
  - name: main
    image: nginx
    ports:
    - containerPort: 80
