- name: nginx 설치 및 구동
  hosts: web
  become: true
  tasks:
    - name: nginx 설치
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: 홈페이지 내용 교체
      copy:
        content: "Hello Ansible! 내가 만든 첫 플레이북\n"
        dest: /var/www/html/index.nginx-debian.html
      notify: restart nginx

    - name: nginx 기동 + 부팅 시 자동시작
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
